In [30]:
import pandas as pd
import numpy as np
import datetime
from openpyxl import load_workbook

In [31]:
SEASON = 11
MATCHDAY = 20

In [32]:
mc = pd.read_excel('data/match_'+str(MATCHDAY)+'.xlsx')
mc.drop('№', axis=1, inplace=True)
mc.rename(columns={'index': 'Name'}, inplace=True)

In [33]:
mc.columns

Index(['Name', 'Итог', 'шарлеруа – андерлехт', '1\n0', 'эвертон – арсенал',
       '2\n1', 'байер – бавария', '1\n2', 'витесс – фейеноорд', '1\n0.1',
       'страсбур – бордо', '0\n2', 'гранада – бетис', '2\n0',
       'аталанта – рома', '4\n1', 'вольфсбург – штутгарт', '1\n0.2',
       'лацио – наполи', '2\n0.1', 'лилль – псж', '0\n0'],
      dtype='object')

In [34]:
#Заголовки нулевой таблицы для создания ДБ ставок
zeros_col = ['Total Points', 'Game Points', 'Bomb Points', 'Exact Score', 'Right Margin', 'Right Result', 'Wrong Result', 'Uniques']

matches = pd.read_excel('output/season_11.xlsx', sheet_name='matches', index_col=0)
players = pd.read_excel('output/season_11.xlsx', sheet_name='players', index_col=0)
season = pd.read_excel('output/season_11.xlsx', sheet_name='season', index_col=0)
teams = pd.read_excel('output/season_11.xlsx', sheet_name='teams', index_col=0)

In [35]:
def proceed_bet(player_id, match_id):
    """
    proceed_bet(player_id, match_id)
    Сверяет ставки с результатом матча.
    player_id = Id участника
    match_id = Id матча
    """
    player_name = players['Name'].iloc[player_id]
    
    h_team = matches['Hometeam'].loc[match_id]
    a_team = matches['Awayteam'].loc[match_id]
    match = str(h_team)+' - '+str(a_team)
    
    try:
        hscore_true = matches['H_score'].loc[match_id]
        ascore_true = matches['A_score'].loc[match_id]

        hscore_bet = int(bets['bet_hscore_'+str(match_id)].loc[player_id])
        ascore_bet = int(bets['bet_ascore_'+str(match_id)].loc[player_id])
        
    except ValueError:
        print(player_name, 'made no bet on', match)
        bets['points_'+str(match_id)].loc[player_id] = 0
        return
    
    true_score= str(hscore_true)+':'+str(ascore_true)
    bet_score= str(hscore_bet)+':'+str(ascore_bet)
    
    points_granted = 0
    
    if (hscore_true == hscore_bet and ascore_true == ascore_bet):
        points_granted = 5
        matches['Exact Score'].loc[match_id] += 1
        season['Exact Score'].loc[player_id] += 1
        bets['Exact Score'].loc[player_id] += 1
    elif (hscore_true - ascore_true) == (hscore_bet - ascore_bet):
        points_granted = 3
        matches['Right Margin'].loc[match_id] += 1
        season['Right Margin'].loc[player_id] += 1
        bets['Right Margin'].loc[player_id] += 1
    elif ((hscore_true > ascore_true) and (hscore_bet > ascore_bet)) or ((hscore_true < ascore_true) and (hscore_bet < ascore_bet)):
        points_granted = 2
        matches['Right Result'].loc[match_id] += 1
        season['Right Result'].loc[player_id] += 1
        bets['Right Result'].loc[player_id] += 1
    else:
        matches['Wrong Result'].loc[match_id] += 1
        season['Wrong Result'].loc[player_id] += 1
        bets['Wrong Result'].loc[player_id] += 1
    matches['Bets'].loc[match_id] += 1
    season['Bets'].loc[player_id] += 1
    bets['points_'+str(match_id)].loc[player_id] = points_granted
    return

def count_total(player_id):
    """
    Считает суммарное число баллов, суммируя значения с bets 
    """
    total = 0
    for i in range(11, bets.shape[1], 3):
        total += bets.loc[player_id].iloc[i]
    bets['Game Points'].loc[player_id] = total
    season['Game Points'].loc[player_id] += total
    print(bets.iloc[player_id, 0], total)
    
def find_uniques(match_ids):
    h_score = str(matches['H_score'].loc[match_ids])
    a_score = str(matches['A_score'].loc[match_ids])
    player_id = bets[bets['bet_hscore_'+str(match_ids)] == h_score][bets['bet_ascore_'+str(match_ids)] == a_score].index[0]
    bets['Uniques'].loc[player_id] += 1
    season['Uniques'].loc[player_id] += 1
    matches['Uniques'].iloc[match_ids] += 1
    return player_id

def get_match_ids(season=SEASON, matchday=MATCHDAY):
    ids = matches[matches['Season'] == season][matches['Matchday'] == matchday].index
    return_list = ['Name', 'Total Points', 'Game Points', 'Bomb Points', 'Exact Score', 'Right Margin', 'Right Result', 'Wrong Result', 'Uniques']
    for i in ids:
        return_list.append('bet_hscore_'+str(i))
        return_list.append('bet_ascore_'+str(i))
        return_list.append('points_'+str(i))
    return return_list

In [36]:
for match, score in zip(mc.columns[2::2], mc.columns[3::2]):
    hometeam, awayteam = match.split(' – ')[0], match.split(' – ')[1]
    h_score, a_score = score.split('\n')[0], score.split('\n')[1][0]
      
    if matches[matches['Matchday'] == MATCHDAY][matches['Hometeam'] == hometeam][matches['Awayteam'] == awayteam].shape[0] > 0:
        print(f'{hometeam} - {awayteam} уже есть')
    else:
        matches = matches.append({'Hometeam': hometeam, 'Awayteam': awayteam,
                                  'H_score': int(h_score), 'A_score': int(a_score),
                                  'Season': SEASON, 'Matchday': MATCHDAY, 'Date': datetime.datetime.now(), 'Bets': 0,
                                  'Exact Score': 0, 'Right Margin': 0, 'Right Result': 0, 
                                  'Wrong Result': 0, 'Uniques': 0}, ignore_index=True)
    
bets_columns = get_match_ids(SEASON,MATCHDAY)
bets = pd.DataFrame(pd.concat([mc['Name'], pd.DataFrame(np.zeros((mc['Name'].shape[0],8)), columns=zeros_col)], axis=1), columns=bets_columns)  

#Очень тупо, я повторяю цикл, потому что между этими операциями ме надо добавить БД для ставок
for match, score in zip(mc.columns[2::2], mc.columns[3::2]):
    hometeam, awayteam = match.split(' – ')[0], match.split(' – ')[1]
    h_score, a_score = score.split('\n')[0], score.split('\n')[1][0]    
    match_id = matches[matches['Hometeam'] == hometeam][matches['Awayteam'] == awayteam].index[0]   
    
    bets['bet_hscore_'+str(match_id)] = mc[match].str.split(':').str[0]
    bets['bet_ascore_'+str(match_id)] = mc[match].str.split(':').str[1]

<ipython-input-36-7dd6f4ee2aab>:5: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  if matches[matches['Matchday'] == MATCHDAY][matches['Hometeam'] == hometeam][matches['Awayteam'] == awayteam].shape[0] > 0:
<ipython-input-36-7dd6f4ee2aab>:5: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  if matches[matches['Matchday'] == MATCHDAY][matches['Hometeam'] == hometeam][matches['Awayteam'] == awayteam].shape[0] > 0:
<ipython-input-36-7dd6f4ee2aab>:5: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  if matches[matches['Matchday'] == MATCHDAY][matches['Hometeam'] == hometeam][matches['Awayteam'] == awayteam].shape[0] > 0:
<ipython-input-36-7dd6f4ee2aab>:5: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  if matches[matches['Matchday'] == MATCHDAY][matches['Hometeam'] == hometeam][matches['Awayteam'] == awayteam].shape[0] > 0:
<ipython-input-36-7dd6f4ee2aab>:5: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  if matches[matches['Matchday'] == MATCHDAY][matches['Hometeam'] == hometeam][matches['Awayteam'] == awayteam].shape[0] > 0:
<ipython-input-36-7dd6f4ee2aab>:5: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  if matches[matches['Matchday'] == MATCHDAY][matches['Hometeam'] == hometeam][matches['Awayteam'] == awayteam].shape[0] > 0:
<ipython-input-36-7dd6f4ee2aab>:5: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  if matches[matches['Matchday'] == MATCHDAY][matches['Hometeam'] == hometeam][matches['Awayteam'] == awayteam].shape[0] > 0:
<ipython-input-36-7dd6f4ee2aab>:5: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  if matches[matches['Matchday'] == MATCHDAY][matches['Hometeam'] == hometeam][matches['Awayteam'] == awayteam].shape[0] > 0:
<ipython-input-36-7dd6f4ee2aab>:5: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  if matches[matches['Matchday'] == MATCHDAY][matches['Hometeam'] == hometeam][matches['Awayteam'] == awayteam].shape[0] > 0:
<ipython-input-36-7dd6f4ee2aab>:5: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  if matches[matches['Matchday'] == MATCHDAY][matches['Hometeam'] == hometeam][matches['Awayteam'] == awayteam].shape[0] > 0:
<ipython-input-36-7dd6f4ee2aab>:21: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  match_id = matches[matches['Hometeam'] == hometeam][matches['Awayteam'] == awayteam].index[0]

In [37]:
for player in range(0,players['Name'].shape[0]):
    for match in matches[matches['Season']==SEASON][matches['Matchday']==MATCHDAY].index:
        proceed_bet(player,match)

H:\dev\py\python-3.8.5.amd64\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
H:\dev\py\python-3.8.5.amd64\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
H:\dev\py\python-3.8.5.amd64\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
H:\dev\py\python-3.8.5.amd64\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
H:\dev\py\python-3.8.5.amd64\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
H:\dev\py\python-3.8.5.amd64\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
H:\dev\py\python-3.8.5.amd64\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
H:\dev\py\python-3.8.5.amd64\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
H:\dev\py\python-3.8.5.amd64\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
H:\dev\py\python-3.8.5.amd64\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
H:\dev\py\python-3.8.5.amd64\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
H:\dev\py\python-3.8.5.amd64\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
H:\dev\py\python-3.8.5.amd64\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
H:\dev\py\python-3.8.5.amd64\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
H:\dev\py\python-3.8.5.amd64\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
H:\dev\py\python-3.8.5.amd64\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
H:\dev\py\python-3.8.5.amd64\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
H:\dev\py\python-3.8.5.amd64\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
H:\dev\py\python-3.8.5.amd64\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
H:\dev\py\python-3.8.5.amd64\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)

Бакланов Сергей made no bet on шарлеруа - андерлехт
Бакланов Сергей made no bet on эвертон - арсенал
Бакланов Сергей made no bet on байер - бавария
Бакланов Сергей made no bet on витесс - фейеноорд
Бакланов Сергей made no bet on страсбур - бордо
Бакланов Сергей made no bet on гранада - бетис
Бакланов Сергей made no bet on аталанта - рома
Бакланов Сергей made no bet on вольфсбург - штутгарт
Бакланов Сергей made no bet on лацио - наполи
Бакланов Сергей made no bet on лилль - псж
Белькин Сергей made no bet on шарлеруа - андерлехт
Белькин Сергей made no bet on эвертон - арсенал
Белькин Сергей made no bet on байер - бавария
Белькин Сергей made no bet on витесс - фейеноорд
Белькин Сергей made no bet on страсбур - бордо
Белькин Сергей made no bet on гранада - бетис
Белькин Сергей made no bet on аталанта - рома
Белькин Сергей made no bet on вольфсбург - штутгарт
Белькин Сергей made no bet on лацио - наполи
Белькин Сергей made no bet on лилль - псж
Дублицевич Александр made no bet on шарлеруа - андерлехт
Дублицевич Александр made no bet on эвертон - арсенал
Дублицевич Александр made no bet on байер - бавария
Дублицевич Александр made no bet on витесс - фейеноорд
Дублицевич Александр made no bet on страсбур - бордо
Дублицевич Александр made no bet on гранада - бетис
Дублицевич Александр made no bet on аталанта - рома
Дублицевич Александр made no bet on вольфсбург - штутгарт
Дублицевич Александр made no bet on лацио - наполи
Дублицевич Александр made no bet on лилль - псж
Зенин Максим made no bet on шарлеруа - андерлехт
Зенин Максим made no bet on эвертон - арсенал
Зенин Максим made no bet on байер - бавария
Зенин Максим made no bet on витесс - фейеноорд
Зенин Максим made no bet on страсбур - бордо
Зенин Максим made no bet on гранада - бетис
Зенин Максим made no bet on аталанта - рома
Зенин Максим made no bet on вольфсбург - штутгарт
Зенин Максим made no bet on лацио - наполи
Зенин Максим made no bet on лилль - псж
Кузнецов Кирилл made no bet on шарлеруа - андерлехт
Кузнецов Кирилл made no bet on эвертон - арсенал
Кузнецов Кирилл made no bet on байер - бавария
Кузнецов Кирилл made no bet on витесс - фейеноорд
Кузнецов Кирилл made no bet on страсбур - бордо
Кузнецов Кирилл made no bet on гранада - бетис
Кузнецов Кирилл made no bet on аталанта - рома
Кузнецов Кирилл made no bet on вольфсбург - штутгарт
Кузнецов Кирилл made no bet on лацио - наполи
Кузнецов Кирилл made no bet on лилль - псж
Муратов Игорь made no bet on шарлеруа - андерлехт
Муратов Игорь made no bet on эвертон - арсенал
Муратов Игорь made no bet on байер - бавария
Холод Максим made no bet on шарлеруа - андерлехт
Холод Максим made no bet on эвертон - арсенал
Холод Максим made no bet on байер - бавария
Холод Максим made no bet on витесс - фейеноорд
Холод Максим made no bet on страсбур - бордо
Холод Максим made no bet on гранада - бетис
Холод Максим made no bet on аталанта - рома
Холод Максим made no bet on вольфсбург - штутгарт
Холод Максим made no bet on лацио - наполи
Холод Максим made no bet on лилль - псж
Язынин Алексей made no bet on шарлеруа - андерлехт
Язынин Алексей made no bet on эвертон - арсенал
Язынин Алексей made no bet on байер - бавария
Язынин Алексей made no bet on витесс - фейеноорд
Язынин Алексей made no bet on страсбур - бордо
Язынин Алексей made no bet on гранада - бетис
Язынин Алексей made no bet on аталанта - рома
Язынин Алексей made no bet on вольфсбург - штутгарт
Язынин Алексей made no bet on лацио - наполи
Язынин Алексей made no bet on лилль - псж

H:\dev\py\python-3.8.5.amd64\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
H:\dev\py\python-3.8.5.amd64\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
H:\dev\py\python-3.8.5.amd64\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
H:\dev\py\python-3.8.5.amd64\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
H:\dev\py\python-3.8.5.amd64\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
H:\dev\py\python-3.8.5.amd64\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
H:\dev\py\python-3.8.5.amd64\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
H:\dev\py\python-3.8.5.amd64\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
H:\dev\py\python-3.8.5.amd64\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
H:\dev\py\python-3.8.5.amd64\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
H:\dev\py\python-3.8.5.amd64\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)

In [38]:
mc

,Name,Итог,шарлеруа – андерлехт,1\n0,эвертон – арсенал,2\n1,байер – бавария,1\n2,витесс – фейеноорд,1\n0.1,...,гранада – бетис,2\n0,аталанта – рома,4\n1,вольфсбург – штутгарт,1\n0.2,лацио – наполи,2\n0.1,лилль – псж,0\n0
0,Андреев Иван,6.0,0:0,0.0,0:0,0.0,0:0,0.0,0:0,0.0,...,0:0,0.0,0:0,0.0,0:0,0.0,0:0,0.0,0:0,6.0
1,Афанасьев Владимир,7.0,0:2,0.0,1:0,3.0,1:1,0.0,1:2,0.0,...,1:1,0.0,2:1,2.0,1:2,0.0,2:1,2.0,1:2,0.0
2,Бакланов Сергей,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Белькин Сергей,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Гришин Антон,13.0,1:1,0.0,2:1,5.0,1:2,5.0,1:1,0.0,...,1:1,0.0,1:1,0.0,1:1,0.0,1:2,0.0,1:1,3.0
5,Дублицевич Александр,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Еременко Владислав,14.0,1:1,0.0,1:0,3.0,0:2,2.0,2:3,0.0,...,1:0,2.0,2:1,2.0,1:0,5.0,1:2,0.0,1:0,0.0
7,Жигалов Александр,3.0,1:1,0.0,1:1,0.0,1:1,0.0,1:1,0.0,...,1:1,0.0,1:1,0.0,1:1,0.0,1:1,0.0,1:1,3.0
8,Зенин Максим,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Зубатов Михаил,7.0,1:2,0.0,1:2,0.0,1:2,5.0,1:2,0.0,...,1:2,0.0,1:2,0.0,1:2,0.0,1:2,0.0,1:2,0.0
10,Колодин Дмитрий,8.0,3:3,0.0,5:1,2.0,3:3,0.0,2:1,3.0,...,3:3,0.0,2:5,0.0,5:5,0.0,4:4,0.0,4:4,3.0
11,Конаков Никита,14.0,1:4,0.0,3:1,2.0,0:1,3.0,2:4,0.0,...,2:3,0.0,4:2,2.0,3:0,2.0,2:2,0.0,3:3,3.0
12,Котов Александр,15.0,0:1,0.0,2:1,5.0,2:1,0.0,1:0,5.0,...,0:1,0.0,1:2,0.0,1:0,5.0,1:2,0.0,1:2,0.0
13,Криеванс Владислав,14.0,0:1,0.0,2:1,5.0,2:4,2.0,2:1,3.0,...,2:1,2.0,1:1,0.0,3:1,2.0,1:2,0.0,1:3,0.0
14,Кузнецов Кирилл,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Кучеренко Никита,20.0,2:1,3.0,2:0,2.0,1:2,5.0,0:1,0.0,...,2:1,2.0,2:1,2.0,2:2,0.0,1:1,0.0,0:2,0.0
16,Лесик Константин,18.0,19:18,3.0,17:16,3.0,15:14,0.0,13:12,3.0,...,9:8,2.0,7:6,2.0,5:4,3.0,3:2,2.0,1:0,0.0
17,Махмудов Руслан,18.0,2:1,3.0,2:0,2.0,2:2,0.0,1:0,5.0,...,1:2,0.0,1:1,0.0,2:1,3.0,2:1,2.0,2:2,3.0
18,Минеев Иван,13.0,1:2,0.0,3:1,2.0,1:3,2.0,2:1,3.0,...,2:1,2.0,2:1,2.0,3:1,2.0,0:2,0.0,1:3,0.0
19,Муратов Игорь,3.0,NaN,0.0,NaN,0.0,NaN,0.0,1:2,0.0,...,1:2,0.0,1:1,0.0,2:1,3.0,1:2,0.0,1:3,0.0
20,Невский Леонид,10.0,1:1,0.0,1:1,0.0,1:2,5.0,1:1,0.0,...,2:1,2.0,1:2,0.0,2:1,3.0,1:2,0.0,1:2,0.0
21,Новиков Александр,13.0,0:1,0.0,2:0,2.0,2:3,3.0,2:1,3.0,...,1:1,0.0,4:3,2.0,2:1,3.0,2:3,0.0,1:4,0.0
22,Оксанич Кирилл,7.0,1:2,0.0,1:2,0.0,1:2,5.0,1:2,0.0,...,1:2,0.0,1:2,0.0,1:2,0.0,1:2,0.0,1:2,0.0
23,Сибиряков Георгий,13.0,1:1,0.0,1:1,0.0,1:2,5.0,1:2,0.0,...,1:1,0.0,2:1,2.0,2:1,3.0,1:2,0.0,1:1,3.0
24,Синичкин Александр,7.0,1:2,0.0,0:1,0.0,1:2,5.0,1:2,0.0,...,1:0,2.0,1:1,0.0,1:1,0.0,0:1,0.0,1:3,0.0
25,Титаренко Антон,7.0,1:1,0.0,1:1,0.0,2:2,0.0,1:1,0.0,...,2:1,2.0,2:1,2.0,2:1,3.0,1:1,0.0,0:2,0.0
26,Фёдоров Владимир,10.0,1:1,0.0,1:1,0.0,1:2,5.0,1:1,0.0,...,1:1,0.0,2:1,2.0,2:1,3.0,1:1,0.0,1:2,0.0
27,Холод Максим,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Чапаров Александр,16.0,1:0,6.0,2:1,5.0,2:2,0.0,3:1,2.0,...,2:2,0.0,0:1,0.0,2:1,3.0,1:1,0.0,2:1,0.0
29,Шевчук Антон,7.0,1:1,0.0,2:1,5.0,2:1,0.0,1:1,0.0,...,1:1,0.0,1:2,0.0,1:1,0.0,1:1,0.0,1:3,0.0
30,Язынин Алексей,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
bets['Name']

0             Андреев Иван
1       Афанасьев Владимир
2          Бакланов Сергей
3           Белькин Сергей
4             Гришин Антон
5     Дублицевич Александр
6       Еременко Владислав
7        Жигалов Александр
8             Зенин Максим
9           Зубатов Михаил
10         Колодин Дмитрий
11          Конаков Никита
12         Котов Александр
13      Криеванс Владислав
14         Кузнецов Кирилл
15        Кучеренко Никита
16        Лесик Константин
17         Махмудов Руслан
18             Минеев Иван
19           Муратов Игорь
20          Невский Леонид
21       Новиков Александр
22          Оксанич Кирилл
23       Сибиряков Георгий
24      Синичкин Александр
25         Титаренко Антон
26        Фёдоров Владимир
27            Холод Максим
28       Чапаров Александр
29            Шевчук Антон
30          Язынин Алексей
Name: Name, dtype: object

In [10]:
bets.iloc[17,14] = 7

In [11]:
bets.iloc[28,23] = 6
bets.iloc[11,23] = 6
bets.iloc[16,23] = 6

In [12]:
bets.iloc[3,38] = 5

In [39]:
for i in matches[matches['Season']==SEASON][matches['Matchday']==MATCHDAY][matches['Exact Score']==1].index:
    player_id = find_uniques(i)
    bets['points_'+str(i)].loc[player_id] += 1
    
for player in range(0,players['Name'].shape[0]):
    count_total(player)

Андреев Иван 6.0
Афанасьев Владимир 7.0
Бакланов Сергей 0.0
Белькин Сергей 0.0
Гришин Антон 13.0
Дублицевич Александр 0.0
Еременко Владислав 14.0
Жигалов Александр 3.0
Зенин Максим 0.0
Зубатов Михаил 7.0
Колодин Дмитрий 8.0
Конаков Никита 14.0
Котов Александр 15.0
Криеванс Владислав 14.0
Кузнецов Кирилл 0.0
Кучеренко Никита 20.0
Лесик Константин 18.0
Махмудов Руслан 18.0
Минеев Иван 13.0
Муратов Игорь 3.0
Невский Леонид 10.0
Новиков Александр 13.0
Оксанич Кирилл 7.0
Сибиряков Георгий 13.0
Синичкин Александр 7.0
Титаренко Антон 7.0
Фёдоров Владимир 10.0
Холод Максим 0.0
Чапаров Александр 16.0
Шевчук Антон 7.0
Язынин Алексей 0.0

<ipython-input-39-c524e9ee286a>:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  for i in matches[matches['Season']==SEASON][matches['Matchday']==MATCHDAY][matches['Exact Score']==1].index:
<ipython-input-35-0ecd95017322>:69: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  player_id = bets[bets['bet_hscore_'+str(match_ids)] == h_score][bets['bet_ascore_'+str(match_ids)] == a_score].index[0]
H:\dev\py\python-3.8.5.amd64\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)

### Bombers

In [40]:
bombs = pd.read_excel('output/bombs_bets.xlsx', index_col=0, sheet_name=str(MATCHDAY))

In [41]:
# Сгрупировал таблицу в формате имя - очки и присвоил в новую переменную
bombs_points = bombs[bombs['Points']>0].groupby(['Name']).sum().sort_values(by=['Points'], ascending=False)

# Теперь итерируем по всей таблице bets. Если имя есть в bomb_points обновляем значение таблицы Bomb Points. 
# Важно вызывать через loc чтобы не вызывать копию, а работать напрямую с табилцей
print('Очки полученные за бомбардиров')
for row in np.arange(bets.shape[0]):
    try:
        bets.loc[row,'Bomb Points'] = bombs_points['Points'][bets.loc[row,'Name']]
        print(bets.loc[row,'Bomb Points'], bets.loc[row,'Name'])
    except KeyError:
        pass

Очки полученные за бомбардиров
1.0 Афанасьев Владимир
2.0 Зубатов Михаил
1.0 Колодин Дмитрий
2.0 Конаков Никита
1.0 Кучеренко Никита
2.0 Минеев Иван
2.0 Сибиряков Георгий
2.0 Титаренко Антон
2.0 Фёдоров Владимир
2.0 Чапаров Александр

In [42]:
bets['Total Points'] = bets['Game Points'] + bets['Bomb Points']

season['Bomb Points'] += bets['Bomb Points']
season['Total Points'] = season['Game Points'] + season['Bomb Points']

In [43]:
bets.sort_values(by=['Total Points'], ascending=False)[['Name','Total Points']]

                    Name  Total Points
15      Кучеренко Никита          21.0
28     Чапаров Александр          18.0
17       Махмудов Руслан          18.0
16      Лесик Константин          18.0
11        Конаков Никита          16.0
18           Минеев Иван          15.0
23     Сибиряков Георгий          15.0
12       Котов Александр          15.0
13    Криеванс Владислав          14.0
6     Еременко Владислав          14.0
4           Гришин Антон          13.0
21     Новиков Александр          13.0
26      Фёдоров Владимир          12.0
20        Невский Леонид          10.0
9         Зубатов Михаил           9.0
25       Титаренко Антон           9.0
10       Колодин Дмитрий           9.0
1     Афанасьев Владимир           8.0
24    Синичкин Александр           7.0
29          Шевчук Антон           7.0
22        Оксанич Кирилл           7.0
0           Андреев Иван           6.0
19         Муратов Игорь           3.0
7      Жигалов Александр           3.0
14       Кузнецов Кирилл           0.0
8           Зенин Максим           0.0
5   Дублицевич Александр           0.0
27          Холод Максим           0.0
3         Белькин Сергей           0.0
2        Бакланов Сергей           0.0
30        Язынин Алексей           0.0

In [44]:
season.sort_values(by=['Total Points'], ascending=False)[['Name','Total Points']]

                    Name  Total Points
23    ﻿Сибиряков Георгий         376.0
18           Минеев Иван         351.0
20        Невский Леонид         344.0
26      Фёдоров Владимир         341.0
25       Титаренко Антон         339.0
15      Кучеренко Никита         329.0
24    Синичкин Александр         328.0
16      Лесик Константин         327.0
9         Зубатов Михаил         320.0
22        Оксанич Кирилл         310.0
4           Гришин Антон         308.0
29          Шевчук Антон         307.0
1     Афанасьев Владимир         306.0
6     Еременко Владислав         306.0
12       Котов Александр         304.0
17       Махмудов Руслан         303.0
7      Жигалов Александр         295.0
5   Дублицевич Александр         290.0
19         Муратов Игорь         284.0
11        Конаков Никита         284.0
13    Криеванс Владислав         284.0
21     Новиков Александр         275.0
3         Белькин Сергей         270.0
30        Язынин Алексей         270.0
28     Чапаров Александр         268.0
2        Бакланов Сергей         259.0
0           Андреев Иван         247.0
10       Колодин Дмитрий         238.0
8           Зенин Максим         230.0
14       Кузнецов Кирилл         137.0
27          Холод Максим         123.0

In [45]:
for match_id in matches[matches['Season']==SEASON][matches['Matchday']==MATCHDAY].index:
    match = matches.iloc[match_id,:]
    hometeam, awayteam = match[0], match[1]
    m_s = matches.iloc[match_id,:]    #Match_series
    for team in [hometeam, awayteam]:
        # Какое говно)))))
        if team == m_s['Hometeam']:
            if m_s['H_score'] > m_s['A_score']:
                win, draw, loss = 1,0,0
            elif m_s['H_score'] < m_s['A_score']:
                win, draw, loss = 0,0,1
            else:
                win, draw, loss = 0,1,0
        elif team == m_s['Awayteam']:
            if m_s['H_score'] > m_s['A_score']:
                win, draw, loss = 0,0,1
            elif m_s['H_score'] < m_s['A_score']:
                win, draw, loss = 1,0,0
            else:
                win, draw, loss = 0,1,0
                      
        if team in teams['Team'].values:
            team_index = teams[teams['Team'] == team].index[0]
            teams.iloc[team_index,2] += 1
            teams.iloc[team_index,3] += win
            teams.iloc[team_index,4] += draw
            teams.iloc[team_index,5] += loss
            teams.iloc[team_index,6] += m_s['Bets']
            teams.iloc[team_index,7] += m_s['Exact Score']
            teams.iloc[team_index,8] += m_s['Right Margin']
            teams.iloc[team_index,9] += m_s['Right Result']
            teams.iloc[team_index,10] += m_s['Wrong Result']
            teams.iloc[team_index,11] += m_s['Uniques']
        else:
            teams = teams.append({'Team': team, 'Matches': 1, 'Wins': win, 'Draws': draw, 'Losses': loss,
                                 'Bets': m_s['Bets'], 'Exact Score': m_s['Exact Score'], 'Right Margin': m_s['Right Margin'], 
                                 'Right Result': m_s['Right Result'], 'Wrong Result': m_s['Wrong Result'], 
                                 'Uniques': m_s['Uniques']}, ignore_index=True)

In [46]:
teams

,Team,Country,Matches,Wins,Draws,Losses,Bets,Exact Score,Right Margin,Right Result,Wrong Result,Uniques
0,гранада,NaN,2,2,0,0,55,0,0,17,38,0
1,атлетик,NaN,5,2,2,1,147,15,14,27,91,0
2,вест хэм,NaN,3,2,0,1,85,13,5,6,61,1
3,ньюкасл юнайтед,NaN,2,2,0,0,61,2,2,15,42,2
4,кристал пэлас,NaN,1,1,0,0,31,1,4,0,26,1
...,...,...,...,...,...,...,...,...,...,...,...,...
104,фиорентина,NaN,1,0,1,0,27,8,0,0,19,0
105,сассуоло,NaN,1,0,1,0,27,8,0,0,19,0
106,шарлеруа,NaN,1,1,0,0,23,1,3,0,19,1
107,фейеноорд,NaN,1,0,0,1,24,2,5,1,16,0
108,страсбур,NaN,1,0,0,1,24,1,0,4,19,1

In [47]:
# Create a Pandas Excel writer using XlsxWriter as the engine.
book = load_workbook('output/bets.xlsx')
writer = pd.ExcelWriter('output/bets.xlsx', engine='openpyxl')
writer.book = book

# Write each dataframe to a different worksheet.
bets.to_excel(writer, sheet_name=str(MATCHDAY))

writer.save()
writer.close()

In [48]:
# Create a Pandas Excel writer using XlsxWriter as the engine.
writer = pd.ExcelWriter(f'output/season_{str(SEASON)}.xlsx', engine='xlsxwriter')

# Write each dataframe to a different worksheet.
season.to_excel(writer, sheet_name='season')
matches.to_excel(writer, sheet_name='matches')
players.to_excel(writer, sheet_name='players')
teams.to_excel(writer, sheet_name='teams')
#scorers.to_excel(writer, sheet_name='scorers_18')

writer.save()