In [1]:
import pandas as pd
import numpy as np
import datetime

Достаем бомберов чтобы не проебать при записи

In [93]:

bombs_1 = pd.read_excel('output/bombs.xlsx', sheet_name="1", index_col=0)
bets_1 = pd.read_excel('output/bombs_bets.xlsx', index_col=0, sheet_name='1')

bets_2 = pd.read_excel('output/bombs_bets.xlsx', index_col=0, sheet_name='2')
bombs_2 = pd.read_excel('output/bombs.xlsx', sheet_name="2", index_col=0)

bets_3 = pd.read_excel('output/bombs_bets.xlsx', index_col=0, sheet_name='3')
bombs_3 = pd.read_excel('output/bombs.xlsx', sheet_name="3", index_col=0)

bets_4 = pd.read_excel('output/bombs_bets.xlsx', index_col=0, sheet_name='4')
bombs_4 = pd.read_excel('output/bombs.xlsx', sheet_name="4", index_col=0)

bets_5 = pd.read_excel('output/bombs_bets.xlsx', index_col=0, sheet_name='5')
bombs_5 = pd.read_excel('output/bombs.xlsx', sheet_name="5", index_col=0)

bets_6 = pd.read_excel('output/bombs_bets.xlsx', index_col=0, sheet_name='6')
bombs_6 = pd.read_excel('output/bombs.xlsx', sheet_name="6", index_col=0)

bets_7 = pd.read_excel('output/bombs_bets.xlsx', index_col=0, sheet_name='7')
bombs_7 = pd.read_excel('output/bombs.xlsx', sheet_name="7", index_col=0)

bets_8 = pd.read_excel('output/bombs_bets.xlsx', index_col=0, sheet_name='8')
bombs_8 = pd.read_excel('output/bombs.xlsx', sheet_name="8", index_col=0)

bets_9 = pd.read_excel('output/bombs_bets.xlsx', index_col=0, sheet_name='9')
bombs_9 = pd.read_excel('output/bombs.xlsx', sheet_name="9", index_col=0)

bets_10 = pd.read_excel('output/bombs_bets.xlsx', index_col=0, sheet_name='10')
bombs_10 = pd.read_excel('output/bombs.xlsx', sheet_name="10", index_col=0)

bets_11 = pd.read_excel('output/bombs_bets.xlsx', index_col=0, sheet_name='11')
bombs_11 = pd.read_excel('output/bombs.xlsx', sheet_name="11", index_col=0)

bets_12 = pd.read_excel('output/bombs_bets.xlsx', index_col=0, sheet_name='12')
bombs_12 = pd.read_excel('output/bombs.xlsx', sheet_name="12", index_col=0)

bets_13 = pd.read_excel('output/bombs_bets.xlsx', index_col=0, sheet_name='13')
bombs_13 = pd.read_excel('output/bombs.xlsx', sheet_name="13", index_col=0)

bets_14 = pd.read_excel('output/bombs_bets.xlsx', index_col=0, sheet_name='14')
bombs_14 = pd.read_excel('output/bombs.xlsx', sheet_name="14", index_col=0)

bets_15 = pd.read_excel('output/bombs_bets.xlsx', index_col=0, sheet_name='15')
bombs_15 = pd.read_excel('output/bombs.xlsx', sheet_name="15", index_col=0)

bets_16 = pd.read_excel('output/bombs_bets.xlsx', index_col=0, sheet_name='16')
bombs_16 = pd.read_excel('output/bombs.xlsx', sheet_name="16", index_col=0)

bets_17 = pd.read_excel('output/bombs_bets.xlsx', index_col=0, sheet_name='17')
bombs_17 = pd.read_excel('output/bombs.xlsx', sheet_name="17", index_col=0)

bets_18 = pd.read_excel('output/bombs_bets.xlsx', index_col=0, sheet_name='18')
bombs_18 = pd.read_excel('output/bombs.xlsx', sheet_name="18", index_col=0)
'''
bets_19 = pd.read_excel('output/bombs_bets.xlsx', index_col=0, sheet_name='19')
bombs_19 = pd.read_excel('output/bombs.xlsx', sheet_name="19", index_col=0)

bets_20 = pd.read_excel('output/bombs_bets.xlsx', index_col=0, sheet_name='20')
bombs_20 = pd.read_excel('output/bombs.xlsx', sheet_name="20", index_col=0)

bets_21 = pd.read_excel('output/bombs_bets.xlsx', index_col=0, sheet_name='21')
bombs_21 = pd.read_excel('output/bombs.xlsx', sheet_name="21", index_col=0)

'''

'\nbets_18 = pd.read_excel(\'output/bombs_bets.xlsx\', index_col=0, sheet_name=\'18\')\nbombs_18 = pd.read_excel(\'output/bombs.xlsx\', sheet_name="18", index_col=0)\n\nbets_19 = pd.read_excel(\'output/bombs_bets.xlsx\', index_col=0, sheet_name=\'19\')\nbombs_19 = pd.read_excel(\'output/bombs.xlsx\', sheet_name="19", index_col=0)\n\nbets_20 = pd.read_excel(\'output/bombs_bets.xlsx\', index_col=0, sheet_name=\'20\')\nbombs_20 = pd.read_excel(\'output/bombs.xlsx\', sheet_name="20", index_col=0)\n\nbets_21 = pd.read_excel(\'output/bombs_bets.xlsx\', index_col=0, sheet_name=\'21\')\nbombs_21 = pd.read_excel(\'output/bombs.xlsx\', sheet_name="21", index_col=0)\n\n'

In [3]:
def replace_typos(df):
    df.replace(r'\) ', ')', inplace=True, regex=True)
    df.replace(r'\( ', '(', inplace=True, regex=True)
    df.replace(r' \)', ')', inplace=True, regex=True)
    #df.replace(r'[\w]\( ', r'[\w] \(', inplace=True, regex=True)
    df.replace([r'\(мс\)'], '(манчестер сити)', inplace=True, regex=True)
    df.replace([r'\(мю\)'], '(манчестер юнайтед)', inplace=True, regex=True)
    df.replace([r'\(реал\)'], '(реал мадрид)', inplace=True, regex=True)
    df.replace([r'\(бд\)', r'\(бвб\)'], '(боруссия дортмунд)', inplace=True, regex=True)
    df.replace(['хаффенхайм'], 'хоффенхайм', inplace=True, regex=True)
    df.replace(['ттх'], 'тоттенхэм', inplace=True, regex=True)
    df.replace(['холанн', 'холланд', 'халанд' ], 'холанд', inplace=True, regex=True)
    df.replace(['атм'], 'атлетико мадрид', inplace=True, regex=True)     
    df.replace(['марата'], 'мората', inplace=True, regex=True)
    df.replace(['ман сити'], 'манчестер сити', inplace=True, regex=True)
    df.replace(['мурьель', 'муриель'], 'муриэль', inplace=True, regex=True)
    df.replace(['абамеянг', 'аубамеянг'], 'обамеянг', inplace=True, regex=True)
    df.replace(['марсиаль', 'марсияль'], 'марсьяль', inplace=True, regex=True)
    df.replace(['сорлот'], 'серлот', inplace=True, regex=True)
    df.replace(to_replace=['«', '»', '"'], value='', inplace=True, regex=True)
    df.replace(to_replace=['тоттэнхэм', 'тоттенхем'], value='тоттенхэм', inplace=True, regex=True)
    return df

In [4]:
def transform_excel(matchday):
    """
    Трансформирует эксель из 3 колонок с бомебрами в одну
    """
    print(matchday)
    old_pd = pd.read_excel(f'data/bombs_{str(matchday)}.xlsx', index_col=0)
    raw_bombs = pd.DataFrame(pd.concat([old_pd.loc[:,'Бомбардир'],
                                        old_pd.loc[:,'Бомбардир.1'],
                                        old_pd.loc[:,'Бомбардир.2']], 
                                   axis=0),
                             columns=['Бомбардир'])
    raw_bombs.index.name = 'Name'
    raw_bombs.sort_values('Name', inplace=True)

        
    raw_bombs['Бомбардир'] = replace_typos(raw_bombs['Бомбардир'])
    
    writer = pd.ExcelWriter('data/bombs_'+str(matchday)+'.xlsx', engine='xlsxwriter')
    raw_bombs.to_excel(writer, sheet_name=str(matchday))
    writer.save()   
    
def process_raw_bombs(matchday):  
    raw_bombs = pd.read_excel(f'data/bombs_{str(matchday)}.xlsx', index_col=0)
    raw_bombs['Scorer'] = raw_bombs['Бомбардир'].apply(lambda x: x.split(' (')[0])
    raw_bombs['Team'] = raw_bombs['Бомбардир'].apply(lambda x: x.split(' (')[1][:-1])
    raw_bombs.drop('Бомбардир', axis=1, inplace=True)
    raw_bets = raw_bombs.copy()
    raw_bets['Goals'] = 0
    raw_bets['Points'] = 0
    raw_bets['Unique'] = 0
    raw_bombs = raw_bombs.drop_duplicates('Scorer')
    raw_bombs.set_index(['Scorer'], inplace=True)
    raw_bombs['Goals'] = 0
    raw_bombs['Picks'] = 0
    raw_bombs['Matchday'] = int(matchday)
    return raw_bombs, raw_bets

In [7]:
# Transform all excel
for i in range(1,23):
    transform_excel(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22

In [98]:
def get_uniques(matchday):
    print(len(globals()[f'bombs_{matchday}'].index.unique()), globals()[f'bombs_{matchday}'].index.sort_values().unique())
    print(len(globals()[f'bets_{matchday}']['Team'].unique()), globals()[f'bets_{matchday}']['Team'].sort_values().unique())

bombs_18, bets_18 = process_raw_bombs('18')
get_uniques(18)

30 Index(['агаларов', 'вегхорст', 'вернер', 'дала', 'де брюйне', 'диас', 'жезус',
       'заа', 'мане', 'манелов', 'марез', 'матета', 'маунт', 'милик', 'нкунку',
       'олайинка', 'пайет', 'полоз', 'поульсен', 'сабослаи', 'салах', 'силва',
       'сисей', 'торнстра', 'троссард', 'тэцл', 'фирмино', 'фоден', 'хаверц',
       'чалов'],
      dtype='object', name='Scorer')
18 ['базель' 'бернли' 'брайтон' 'краснодар' 'кристал пэлас' 'ливерпуль'
 'манчестер сити' 'марсель' 'рб лейпциг' 'ростов' 'селтик' 'сити' 'славия'
 'славия прага' 'уфа' 'фейеноорд' 'цюрих' 'челси']

Запись в готовый файл для ручной простановки голов

In [99]:
## Bets excel

# Create a Pandas Excel writer using XlsxWriter as the engine.
with pd.ExcelWriter('output/bombs_bets.xlsx', engine='xlsxwriter') as writer:

    # Write each dataframe to a different worksheet.
    bets_1.to_excel(writer, sheet_name='1')
    bets_2.to_excel(writer, sheet_name='2')
    bets_3.to_excel(writer, sheet_name='3')
    bets_4.to_excel(writer, sheet_name='4')
    bets_5.to_excel(writer, sheet_name='5')
    bets_6.to_excel(writer, sheet_name='6')
    bets_7.to_excel(writer, sheet_name='7')
    bets_8.to_excel(writer, sheet_name='8')
    bets_9.to_excel(writer, sheet_name='9')
    bets_10.to_excel(writer, sheet_name='10')
    bets_11.to_excel(writer, sheet_name='11')
    bets_12.to_excel(writer, sheet_name='12')
    bets_13.to_excel(writer, sheet_name='13')
    bets_14.to_excel(writer, sheet_name='14')
    bets_15.to_excel(writer, sheet_name='15')
    bets_16.to_excel(writer, sheet_name='16')
    bets_17.to_excel(writer, sheet_name='17')
    bets_18.to_excel(writer, sheet_name='18')
    '''
    bets_19.to_excel(writer, sheet_name='19')
    bets_20.to_excel(writer, sheet_name='20')
    '''
    writer.save()

# Create a Pandas Excel writer using XlsxWriter as the engine.
with pd.ExcelWriter('output/bombs.xlsx', engine='xlsxwriter') as writer:

    # Write each dataframe to a different worksheet.
    bombs_1.to_excel(writer, sheet_name='1')
    bombs_2.to_excel(writer, sheet_name='2')
    bombs_3.to_excel(writer, sheet_name='3')
    bombs_4.to_excel(writer, sheet_name='4')
    bombs_5.to_excel(writer, sheet_name='5')
    bombs_6.to_excel(writer, sheet_name='6')
    bombs_7.to_excel(writer, sheet_name='7')
    bombs_8.to_excel(writer, sheet_name='8')
    bombs_9.to_excel(writer, sheet_name='9')
    bombs_10.to_excel(writer, sheet_name='10')
    bombs_11.to_excel(writer, sheet_name='11')
    bombs_12.to_excel(writer, sheet_name='12')
    bombs_13.to_excel(writer, sheet_name='13')
    bombs_14.to_excel(writer, sheet_name='14')
    bombs_15.to_excel(writer, sheet_name='15')
    bombs_16.to_excel(writer, sheet_name='16')
    bombs_17.to_excel(writer, sheet_name='17')
    bombs_18.to_excel(writer, sheet_name='18')
    '''
    bombs_19.to_excel(writer, sheet_name='19')
    bombs_20.to_excel(writer, sheet_name='20')
    '''
    writer.save()

После ручной простановки заново загружаем дату

In [103]:
bets_18 = pd.read_excel('output/bombs_bets.xlsx', index_col=0, sheet_name='18')
bombs_18 = pd.read_excel('output/bombs.xlsx', sheet_name="18", index_col=0)

In [9]:
def count_picks(bets, bombs):
    """
    Считает число пиков бомбера в туре
    """
    for scorer in list(bombs.index):
        picks = len(bets[bets['Scorer'] == scorer])
        bombs['Picks'].loc[scorer] = picks
        
def bomb_points(bets, bombs):
    """
    Начисляет очки
    """    
    scored = list(bombs[bombs['Goals'] > 0].index)

    for i in range(bets.shape[0]):
        scorer = bets['Scorer'].iloc[i]
        if scorer in scored:
            goals = bombs['Goals'].loc[scorer]
            bets.iloc[i, 2] = goals
            if len(bets[bets['Scorer'] == scorer]) == 1:
                points = (goals*2)+2 
                bets.iloc[i, 4] = 1
            else:
                points = goals*2
            bets.iloc[i, 3] = points
            #print(scorer, goals, points)

In [37]:
list(bombs_3[bombs_3['Goals'] > 0].index)

['мбаппе', 'салах', 'стерлинг', 'торрес', 'фоден']

In [9]:
bombs_1.loc['ларсен']

Team        хоффенхайм
Goals                1
Picks                0
Matchday             1
Name: ларсен, dtype: object

In [104]:
count_picks(bets_18, bombs_18)
bomb_points(bets_18, bombs_18)

c:\users\anton.shevchuk\appdata\local\programs\python\python39-32\lib\site-packages\pandas\core\indexing.py:1732: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)

In [105]:
bets_18.groupby("Name").sum()

                    Goals  Points  Unique
Name
Алферов Ян              1       2       0
Гришин Антон            2       6       1
Данилов Евгений         1       2       0
Дробышев Артемий        2       4       0
Зубатов Михаил          0       0       0
Колодин Дмитрий         1       2       0
Конаков Никита          1       2       0
Котов Александр         1       4       1
Криеванс Владислав      0       0       0
Малевич Егор            0       0       0
Махмудов Руслан         0       0       0
Муратов Игорь           1       2       0
Невский Леонид          2       4       0
Сибиряков Георгий       1       4       1
Титаренко Антон         0       0       0
Фёдоров Владимир        1       4       1
Шевчук Антон            1       2       0

In [106]:
## Bets excel

# Create a Pandas Excel writer using XlsxWriter as the engine.
with pd.ExcelWriter('output/bombs_bets.xlsx', engine='xlsxwriter') as writer:

    # Write each dataframe to a different worksheet.
    bets_1.to_excel(writer, sheet_name='1')
    bets_2.to_excel(writer, sheet_name='2')
    bets_3.to_excel(writer, sheet_name='3')
    bets_4.to_excel(writer, sheet_name='4')
    bets_5.to_excel(writer, sheet_name='5')
    bets_6.to_excel(writer, sheet_name='6')
    bets_7.to_excel(writer, sheet_name='7')
    bets_8.to_excel(writer, sheet_name='8')
    bets_9.to_excel(writer, sheet_name='9')
    bets_10.to_excel(writer, sheet_name='10')
    bets_11.to_excel(writer, sheet_name='11')
    bets_12.to_excel(writer, sheet_name='12')
    bets_13.to_excel(writer, sheet_name='13')
    bets_14.to_excel(writer, sheet_name='14')
    bets_15.to_excel(writer, sheet_name='15')
    bets_16.to_excel(writer, sheet_name='16')
    bets_17.to_excel(writer, sheet_name='17')
    bets_18.to_excel(writer, sheet_name='18')
    '''
    bets_19.to_excel(writer, sheet_name='19')
    bets_20.to_excel(writer, sheet_name='20')
    
    '''
    writer.save()

# Create a Pandas Excel writer using XlsxWriter as the engine.
with pd.ExcelWriter('output/bombs.xlsx', engine='xlsxwriter') as writer:

    # Write each dataframe to a different worksheet.
    bombs_1.to_excel(writer, sheet_name='1')
    bombs_2.to_excel(writer, sheet_name='2')
    bombs_3.to_excel(writer, sheet_name='3')
    bombs_4.to_excel(writer, sheet_name='4')
    bombs_5.to_excel(writer, sheet_name='5')
    bombs_6.to_excel(writer, sheet_name='6')
    bombs_7.to_excel(writer, sheet_name='7')
    bombs_8.to_excel(writer, sheet_name='8')
    bombs_9.to_excel(writer, sheet_name='9')
    bombs_10.to_excel(writer, sheet_name='10')
    bombs_11.to_excel(writer, sheet_name='11')
    bombs_12.to_excel(writer, sheet_name='12')
    bombs_13.to_excel(writer, sheet_name='13')
    bombs_14.to_excel(writer, sheet_name='14')
    bombs_15.to_excel(writer, sheet_name='15')
    bombs_16.to_excel(writer, sheet_name='16')
    bombs_17.to_excel(writer, sheet_name='17')
    bombs_18.to_excel(writer, sheet_name='18')
    '''
    bombs_19.to_excel(writer, sheet_name='19')
    bombs_20.to_excel(writer, sheet_name='20')
    '''
    writer.save()

c:\users\anton.shevchuk\appdata\local\programs\python\python39-32\lib\site-packages\xlsxwriter\workbook.py:338: UserWarning: Calling close() on already closed file.
  warn("Calling close() on already closed file.")

In [29]:
allgemein = pd.concat([bombs_2, bombs_18], axis=0, ignore_index=False)
allgemein.groupby(['Team', 'Scorer']).agg({'Goals': 'sum', 'Picks': 'sum', 'Matchday': 'count'}).sort_values('Picks', ascending=False)

NameError: name 'bombs_18' is not defined

In [3]:
bombs_list = [bombs_1, bombs_2, bombs_3, bombs_4, bombs_5, bombs_6, bombs_7, bombs_8, bombs_9, bombs_10, bombs_11, bombs_12, 
              bombs_13, bombs_14, bombs_15, bombs_16, bombs_17, bombs_18, bombs_19, bombs_20, bombs_20]
bets_list = [bets_1, bets_2, bets_3, bets_4, bets_5, bets_6, bets_7, bets_8, bets_9, bets_10, bets_11, bets_12, bets_13,
             bets_14, bets_15, bets_16, bets_17, bets_18, bets_19, bets_20, bets_21]

In [4]:
all_bets = pd.concat(bets_list, axis=0, ignore_index=True)
all_bombs = pd.concat(bombs_list, axis=0, ignore_index=True)

In [5]:
bombs_gb = all_bombs.groupby(['Team', 'Scorer']).agg({'Goals': 'sum', 'Picks': 'sum', 'Matchday': 'count'})
bets_gb = all_bets.groupby('Name').sum()

In [11]:
bombs_gb.sort_values('Picks', ascending=False).head(10)

                               Goals  Picks  Matchday
Team              Scorer
интер             лукаку           4     37         5
лацио             иммобиле         1     28         3
ювентус           роналду          3     27         4
бавария           левандовски      5     27         4
манчестер сити    агуэро           0     27         5
вулверхэмптон     хименес          4     26         8
манчестер сити    стерлинг         2     25         6
аталанта          сапата           2     25         8
манчестер юнайтед фернандеш        2     24         7
боруссия дортмунд холанд           4     24         5

In [12]:
bets_gb.sort_values('Points', ascending=False)

                      Goals  Points  Unique
Name
Конаков Никита           31      34       3
Шевчук Антон             26      29       3
Колодин Дмитрий          23      28       5
Сибиряков Георгий        27      28       1
Лесик Константин         24      28       4
Муратов Игорь            25      27       2
Махмудов Руслан          18      26       8
Титаренко Антон          24      26       2
Гришин Антон             25      26       1
Жигалов Александр        24      26       2
Афанасьев Владимир       25      26       1
Невский Леонид           23      25       2
Чапаров Александр        21      24       3
Дублицевич Александр     23      23       0
Мяло Игорь               20      21       1
Котов Александр          17      21       4
Кучеренко Никита         19      19       0
Ашихмин Михаил           16      17       1
Малевич Егор             14      16       2
Кузнецов Кирилл          12      15       3
Новиков Александр        10      14       4
Фёдоров Владимир         13      14       1
Зубатов Михаил           11      11       0